
package org.wecancodeit.StateFish.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StateServiceSoapService", targetNamespace = "http://Controller.StateFish.wecancodeit.org/", wsdlLocation = "http://localhost:1234/stateservice?wsdl")
public class StateServiceSoapService
    extends Service
{

    private final static URL STATESERVICESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATESERVICESOAPSERVICE_EXCEPTION;
    private final static QName STATESERVICESOAPSERVICE_QNAME = new QName("http://Controller.StateFish.wecancodeit.org/", "StateServiceSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/stateservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATESERVICESOAPSERVICE_WSDL_LOCATION = url;
        STATESERVICESOAPSERVICE_EXCEPTION = e;
    }

    public StateServiceSoapService() {
        super(__getWsdlLocation(), STATESERVICESOAPSERVICE_QNAME);
    }

    public StateServiceSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATESERVICESOAPSERVICE_QNAME, features);
    }

    public StateServiceSoapService(URL wsdlLocation) {
        super(wsdlLocation, STATESERVICESOAPSERVICE_QNAME);
    }

    public StateServiceSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATESERVICESOAPSERVICE_QNAME, features);
    }

    public StateServiceSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StateServiceSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "StateServiceSoapPort")
    public StateService getStateServiceSoapPort() {
        return super.getPort(new QName("http://Controller.StateFish.wecancodeit.org/", "StateServiceSoapPort"), StateService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StateService
     */
    @WebEndpoint(name = "StateServiceSoapPort")
    public StateService getStateServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Controller.StateFish.wecancodeit.org/", "StateServiceSoapPort"), StateService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATESERVICESOAPSERVICE_EXCEPTION!= null) {
            throw STATESERVICESOAPSERVICE_EXCEPTION;
        }
        return STATESERVICESOAPSERVICE_WSDL_LOCATION;
    }

}
